# on:
#   push:
#     tags:
#       - v*

on:
  push:
    branches:
      - actions

jobs:
  build:
    name: build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag pyguy/first-website:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push pyguy/first-website:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag pyguy/first-website:latest
      - name: Push the latest Docker image
        run: docker push pyguy/first-website:latest